import type { ItemKind, TemplateCategoryId, Workflow, WorkflowStep } from "./types";

type W = {
  slug: string; name: string; goal: string; description: string; input: ItemKind; multiple?: boolean; steps: WorkflowStep[];
  output: string; audience: TemplateCategoryId[]; keywords: string[]; icon: string; popular?: boolean; inputLabel?: string;
};

const INPUT_LABEL: Record<ItemKind, string> = { image: "Image", pdf: "PDF", text: "Text", json: "JSON", csv: "CSV" };
const w = (d: W): Workflow => ({ ...d, inputLabel: d.inputLabel || INPUT_LABEL[d.input] });

const size = (width: number, height: number, fit = "cover", background = "#ffffff") => ({ step: "resize", params: { width, height, fit, background } });
const jpg = (quality = 85) => ({ step: "convert", params: { format: "jpeg", quality } });
const webp = (quality = 82) => ({ step: "convert", params: { format: "webp", quality } });
const png = () => ({ step: "convert", params: { format: "png", quality: 100 } });
const strip = { step: "strip-metadata" };
const under = (maxKB: number) => ({ step: "ensure-size", params: { maxKB } });
const crop = (ratio: string) => ({ step: "crop-ratio", params: { ratio } });
const pdfUnder = (maxKB: number) => ({ step: "pdf-ensure-size", params: { maxKB } });

export const WORKFLOWS: Workflow[] = [
  // ── Image: web & social ──
  w({ slug: "website-image", name: "Website Image", icon: "globe", popular: true, input: "image", multiple: true,
    goal: "Make images load fast on a website without visible quality loss.",
    description: "Resizes to a sensible maximum width, converts to modern WebP, compresses and removes private metadata.",
    steps: [size(1600, 1600, "inside"), webp(82), { step: "compress", params: { quality: 80 } }, strip],
    output: "WebP image, max 1600 px, typically 70–90% smaller", audience: ["business", "developers", "creators"],
    keywords: ["website", "web", "site", "optimize", "fast", "seo", "webp", "blog"] }),
  w({ slug: "instagram-post", name: "Instagram Post (Square)", icon: "instagram", popular: true, input: "image", multiple: true,
    goal: "Get a perfectly framed 1:1 Instagram post.", description: "Center-crops to square, sizes to 1080 × 1080 and exports a crisp JPG.",
    steps: [crop("1:1"), size(1080, 1080), jpg(90), strip], output: "1080 × 1080 JPG", audience: ["social-media", "creators"],
    keywords: ["instagram", "insta", "post", "square", "ig"] }),
  w({ slug: "instagram-portrait", name: "Instagram Portrait Post", icon: "instagram", input: "image", multiple: true,
    goal: "Use the tallest feed format Instagram allows.", description: "Crops to 4:5 and sizes to 1080 × 1350 for maximum feed space.",
    steps: [crop("4:5"), size(1080, 1350), jpg(90), strip], output: "1080 × 1350 JPG", audience: ["social-media", "creators"],
    keywords: ["instagram", "portrait", "4:5", "feed"] }),
  w({ slug: "instagram-story", name: "Instagram / WhatsApp Story", icon: "smartphone", input: "image", multiple: true,
    goal: "Fill the whole phone screen in Stories and Status.", description: "Crops to 9:16 and sizes to 1080 × 1920.",
    steps: [crop("9:16"), size(1080, 1920), jpg(88), strip], output: "1080 × 1920 JPG", audience: ["social-media", "creators", "personal"],
    keywords: ["story", "status", "reel", "9:16", "vertical"] }),
  w({ slug: "whatsapp-image", name: "WhatsApp-Ready Image", icon: "send", popular: true, input: "image", multiple: true,
    goal: "Send clear photos that upload quickly and don't reveal your location.", description: "Limits size to 1600 px, compresses to JPG and removes GPS and other metadata.",
    steps: [size(1600, 1600, "inside"), jpg(80), strip, under(400)], output: "JPG under 400 KB, no location data", audience: ["personal", "social-media"],
    keywords: ["whatsapp", "send", "share", "photo", "small"] }),
  w({ slug: "whatsapp-dp", name: "WhatsApp Profile Photo", icon: "user", input: "image",
    goal: "Create a sharp square profile picture.", description: "Square crop at 640 × 640, compressed JPG.",
    steps: [crop("1:1"), size(640, 640), jpg(88), strip], output: "640 × 640 JPG", audience: ["personal", "social-media"],
    keywords: ["dp", "profile", "whatsapp dp", "avatar"] }),
  w({ slug: "profile-picture", name: "Profile Picture (All Platforms)", icon: "user", input: "image",
    goal: "One profile photo that looks good on LinkedIn, Google, X and GitHub.", description: "Square 800 × 800 JPG with metadata removed.",
    steps: [crop("1:1"), size(800, 800), jpg(90), strip], output: "800 × 800 JPG", audience: ["personal", "business", "developers"],
    keywords: ["profile", "avatar", "linkedin photo", "headshot"] }),
  w({ slug: "product-image", name: "Product Image", icon: "bag", popular: true, input: "image", multiple: true,
    goal: "Clean, square product photos for Amazon, Flipkart, Meesho or Shopify.", description: "Removes a plain background to white, centers the product on a 2000 × 2000 square and exports a high-quality JPG.",
    steps: [{ step: "remove-bg", params: { tolerance: 38, fill: "#ffffff" } }, size(2000, 2000, "contain"), jpg(90), strip],
    output: "2000 × 2000 JPG on white", audience: ["business", "creators"], keywords: ["product", "amazon", "flipkart", "ecommerce", "shop", "listing", "meesho"] }),
  w({ slug: "ecommerce-webp", name: "Store Catalog Image (WebP)", icon: "bag", input: "image", multiple: true,
    goal: "Lightweight square images for your online store.", description: "1000 × 1000 square with white padding, WebP, compressed.",
    steps: [size(1000, 1000, "contain"), webp(80), strip], output: "1000 × 1000 WebP", audience: ["business", "developers"],
    keywords: ["store", "catalog", "shopify", "woocommerce", "webp"] }),
  w({ slug: "thumbnail", name: "Thumbnail", icon: "image", input: "image", multiple: true,
    goal: "Small preview images for lists and galleries.", description: "400 × 300 cover crop in WebP.",
    steps: [size(400, 300), webp(75), strip], output: "400 × 300 WebP", audience: ["developers", "creators"],
    keywords: ["thumbnail", "preview", "small image", "gallery"] }),
  w({ slug: "youtube-thumbnail", name: "YouTube Thumbnail", icon: "play", input: "image",
    goal: "Meet YouTube's thumbnail requirements.", description: "1280 × 720 (16:9) JPG under 2 MB.",
    steps: [crop("16:9"), size(1280, 720), jpg(90), under(2000)], output: "1280 × 720 JPG under 2 MB", audience: ["creators", "social-media"],
    keywords: ["youtube", "thumbnail", "yt", "video cover"] }),
  w({ slug: "social-share-image", name: "Link Preview Image (Open Graph)", icon: "share", input: "image",
    goal: "Great-looking link previews on WhatsApp, LinkedIn and Facebook.", description: "1200 × 630 JPG — the standard Open Graph size.",
    steps: [size(1200, 630), jpg(85), strip, under(600)], output: "1200 × 630 JPG", audience: ["developers", "business", "creators"],
    keywords: ["og image", "open graph", "link preview", "share image", "meta image"] }),
  w({ slug: "blog-featured-image", name: "Blog Featured Image", icon: "book", input: "image",
    goal: "Fast, wide hero images for blog posts.", description: "1600 × 900 WebP, compressed with metadata removed.",
    steps: [size(1600, 900), webp(80), strip], output: "1600 × 900 WebP", audience: ["creators", "business"],
    keywords: ["blog", "featured", "hero image", "wordpress"] }),
  w({ slug: "facebook-cover", name: "Facebook Cover Photo", icon: "image", input: "image",
    goal: "A cover that looks sharp on desktop and mobile.", description: "1640 × 624 JPG.",
    steps: [size(1640, 624), jpg(90), strip], output: "1640 × 624 JPG", audience: ["social-media", "business"],
    keywords: ["facebook", "cover", "fb banner"] }),
  w({ slug: "linkedin-banner", name: "LinkedIn Banner", icon: "briefcase", input: "image",
    goal: "A professional LinkedIn background image.", description: "1584 × 396 JPG.",
    steps: [size(1584, 396), jpg(90), strip], output: "1584 × 396 JPG", audience: ["business", "social-media"],
    keywords: ["linkedin", "banner", "background", "header"] }),
  w({ slug: "x-header", name: "X (Twitter) Header", icon: "image", input: "image",
    goal: "The right header size for X.", description: "1500 × 500 JPG.",
    steps: [size(1500, 500), jpg(90), strip], output: "1500 × 500 JPG", audience: ["social-media"],
    keywords: ["twitter", "x", "header", "banner"] }),
  w({ slug: "pinterest-pin", name: "Pinterest Pin", icon: "image", input: "image",
    goal: "Tall pins that stand out.", description: "2:3 crop at 1000 × 1500.",
    steps: [crop("2:3"), size(1000, 1500), jpg(88), strip], output: "1000 × 1500 JPG", audience: ["social-media", "creators"],
    keywords: ["pinterest", "pin"] }),
  w({ slug: "email-photo", name: "Email-Friendly Photos", icon: "mail", input: "image", multiple: true,
    goal: "Attach several photos without hitting email limits.", description: "Limits to 1200 px and compresses each photo.",
    steps: [size(1200, 1200, "inside"), jpg(75), strip], output: "JPG, max 1200 px", audience: ["personal", "business"],
    keywords: ["email", "attach", "photos", "gmail"] }),
  w({ slug: "passport-photo", name: "Passport-Size Photo (35×45 mm)", icon: "user", input: "image",
    goal: "Resize a photo to the common 35 × 45 mm passport ratio for online forms.", description: "Crops to 7:9 at 413 × 531 px (300 DPI) and keeps it under 200 KB. Always check your form's exact rules.",
    steps: [size(413, 531), jpg(90), strip, under(200)], output: "413 × 531 JPG under 200 KB", audience: ["students", "personal", "documents"],
    keywords: ["passport", "photo", "35x45", "visa", "id photo"] }),
  w({ slug: "exam-form-photo", name: "Exam Form Photo (under 50 KB)", icon: "graduation", input: "image",
    goal: "Meet typical exam and job form photo limits.", description: "200 × 230 px JPG under 50 KB — a common requirement for SSC, bank and state exam forms. Check your notification for exact limits.",
    steps: [size(200, 230), jpg(85), strip, under(50)], output: "200 × 230 JPG under 50 KB", audience: ["students", "documents"],
    keywords: ["exam", "form", "ssc", "upsc", "bank", "photo under 50kb", "application photo", "sarkari"] }),
  w({ slug: "signature-for-form", name: "Signature for Online Form", icon: "pen-line", input: "image",
    goal: "Turn a photo of your signature into an upload-ready file.", description: "Cleans the paper background to white, sizes to 280 × 120 and keeps it under 20 KB.",
    steps: [{ step: "remove-bg", params: { tolerance: 55, fill: "#ffffff" } }, size(280, 120, "contain"), jpg(85), under(20)],
    output: "280 × 120 JPG under 20 KB", audience: ["students", "documents"], keywords: ["signature", "sign", "form", "under 20kb"] }),
  w({ slug: "private-photo", name: "Share Photo Without Location", icon: "shield-off", input: "image", multiple: true,
    goal: "Share photos without revealing where they were taken.", description: "Removes GPS, camera and date metadata while keeping full quality.",
    steps: [strip, jpg(95)], output: "Full-quality JPG, no metadata", audience: ["personal"],
    keywords: ["privacy", "location", "gps", "exif", "private"] }),
  w({ slug: "png-to-jpg", name: "PNG to JPG (Batch)", icon: "repeat", input: "image", multiple: true,
    goal: "Convert screenshots and PNGs to smaller JPGs.", description: "Converts every image to high-quality JPG.",
    steps: [jpg(90)], output: "JPG files", audience: ["personal", "business"], keywords: ["png to jpg", "convert", "screenshot"] }),
  w({ slug: "webp-to-png", name: "WebP to PNG", icon: "repeat", input: "image", multiple: true,
    goal: "Open downloaded WebP images in any app.", description: "Converts to lossless PNG.",
    steps: [png()], output: "PNG files", audience: ["personal", "creators"], keywords: ["webp to png", "webp", "open webp"] }),
  w({ slug: "transparent-logo", name: "Transparent Logo", icon: "palette", input: "image",
    goal: "Remove a white or solid background from a logo.", description: "Removes the background and exports a transparent PNG up to 1000 px.",
    steps: [{ step: "remove-bg", params: { tolerance: 35, fill: "transparent" } }, size(1000, 1000, "inside"), png()],
    output: "Transparent PNG", audience: ["business", "creators"], keywords: ["logo", "transparent", "png", "remove white"] }),
  w({ slug: "email-signature-logo", name: "Email Signature Logo", icon: "mail", input: "image",
    goal: "A small, crisp logo for your email signature.", description: "Fits inside 300 × 100 px as PNG.",
    steps: [size(300, 100, "inside"), png()], output: "PNG, max 300 × 100", audience: ["business"], keywords: ["email signature", "logo", "small logo"] }),
  w({ slug: "print-photo-4x6", name: "Print Photo 4×6 in", icon: "printer", input: "image", multiple: true,
    goal: "Prepare photos for 4 × 6 inch prints.", description: "1800 × 1200 px (300 DPI) high-quality JPG.",
    steps: [crop("3:2"), size(1800, 1200), jpg(95)], output: "1800 × 1200 JPG", audience: ["personal"], keywords: ["print", "4x6", "photo print"] }),
  w({ slug: "phone-wallpaper", name: "Phone Wallpaper", icon: "smartphone", input: "image",
    goal: "Fit a photo to a modern phone screen.", description: "1080 × 2400 cover crop.",
    steps: [size(1080, 2400), jpg(90)], output: "1080 × 2400 JPG", audience: ["personal"], keywords: ["wallpaper", "phone", "lock screen"] }),
  w({ slug: "desktop-wallpaper", name: "Desktop Wallpaper (Full HD)", icon: "monitor", input: "image",
    goal: "Fit a photo to a 16:9 desktop screen.", description: "1920 × 1080 cover crop.",
    steps: [crop("16:9"), size(1920, 1080), jpg(92)], output: "1920 × 1080 JPG", audience: ["personal"], keywords: ["wallpaper", "desktop", "1080p"] }),
  w({ slug: "image-under-100kb", name: "Image Under 100 KB", icon: "gauge", input: "image", multiple: true,
    goal: "Hit a strict 100 KB upload limit.", description: "Converts to JPG and lowers quality and size until the file is under 100 KB.",
    steps: [jpg(85), strip, under(100)], output: "JPG under 100 KB", audience: ["students", "documents", "personal"], keywords: ["100kb", "under 100 kb", "reduce kb", "photo size"] }),
  w({ slug: "image-under-1mb", name: "Image Under 1 MB", icon: "gauge", input: "image", multiple: true,
    goal: "Keep photos under 1 MB for uploads and email.", description: "Optimizes each image until it is under 1 MB.",
    steps: [size(3000, 3000, "inside"), jpg(88), under(1000)], output: "JPG under 1 MB", audience: ["personal", "business"], keywords: ["1mb", "under 1 mb", "upload limit"] }),
  w({ slug: "scan-to-pdf", name: "Scanned Pages to PDF", icon: "file-image", popular: true, input: "image", multiple: true,
    goal: "Turn phone photos of documents into one compact PDF.", description: "Combines images into A4 pages and compresses the result.",
    steps: [size(1654, 2339, "inside"), jpg(80), { step: "images-to-pdf", params: { pageSize: "a4", margin: 18 } }],
    output: "One A4 PDF", audience: ["documents", "students", "business"], keywords: ["scan", "photos to pdf", "document", "camscanner"] }),
  w({ slug: "student-assignment-pdf", name: "Student Assignment PDF", icon: "graduation", popular: true, input: "image", multiple: true,
    goal: "Submit handwritten pages as a single, small PDF.", description: "Straightens sizes to A4, merges pages into one PDF and keeps it under 5 MB for portals like Google Classroom.",
    steps: [size(1654, 2339, "inside"), jpg(78), { step: "images-to-pdf", params: { pageSize: "a4", margin: 12 } }, pdfUnder(5000)],
    output: "A4 PDF under 5 MB", audience: ["students", "documents"], keywords: ["assignment", "homework", "student", "classroom", "notes"] }),
  w({ slug: "receipts-to-pdf", name: "Receipts to PDF", icon: "receipt", input: "image", multiple: true,
    goal: "Bundle receipts for expense claims.", description: "One page per receipt, compressed for email.",
    steps: [size(1400, 2000, "inside"), jpg(78), { step: "images-to-pdf", params: { pageSize: "fit", margin: 0 } }, pdfUnder(5000)],
    output: "Single PDF of receipts", audience: ["business", "personal"], keywords: ["receipt", "expense", "bills", "reimbursement"] }),

  // ── PDF ──
  w({ slug: "whatsapp-ready-pdf", name: "WhatsApp-Ready PDF", icon: "send", popular: true, input: "pdf",
    goal: "Make a PDF small enough to send and open quickly on phones.", description: "Compresses the PDF, checks the size and optimizes again if it is still over 2 MB.",
    steps: [{ step: "pdf-compress", params: { mode: "balanced" } }, pdfUnder(2048)], output: "PDF under 2 MB", audience: ["personal", "documents", "students"],
    keywords: ["whatsapp", "pdf", "send pdf", "small pdf"] }),
  w({ slug: "email-ready-pdf", name: "Email-Ready PDF", icon: "mail", popular: true, input: "pdf",
    goal: "Fit a PDF under common email attachment limits.", description: "Keeps quality where possible and targets under 10 MB, which works for Gmail, Outlook and most company mail servers.",
    steps: [{ step: "pdf-compress", params: { mode: "lossless" } }, pdfUnder(10000)], output: "PDF under 10 MB", audience: ["business", "documents"],
    keywords: ["email", "gmail", "attachment", "pdf too large"] }),
  w({ slug: "govt-portal-pdf", name: "Upload-Portal PDF (under 200 KB)", icon: "landmark", input: "pdf",
    goal: "Meet strict government and exam portal limits.", description: "Strong compression down to 200 KB — typical for application and certificate uploads.",
    steps: [{ step: "pdf-compress", params: { mode: "strong" } }, pdfUnder(200)], output: "PDF under 200 KB", audience: ["documents", "students"],
    keywords: ["200kb", "portal", "govt", "government", "certificate", "upload pdf", "sarkari"] }),
  w({ slug: "pdf-under-1mb", name: "PDF Under 1 MB", icon: "gauge", input: "pdf",
    goal: "Get any PDF below 1 MB.", description: "Compresses and re-checks until the file is under 1 MB.",
    steps: [{ step: "pdf-compress", params: { mode: "balanced" } }, pdfUnder(1000)], output: "PDF under 1 MB", audience: ["documents", "students", "business"],
    keywords: ["1mb pdf", "pdf under 1 mb", "reduce pdf"] }),
  w({ slug: "print-ready-document", name: "Print-Ready Document", icon: "printer", input: "pdf",
    goal: "Optimize a PDF for printing without losing sharpness.", description: "Lossless optimization only — text and images stay print quality.",
    steps: [{ step: "pdf-compress", params: { mode: "lossless" } }], output: "Optimized print-quality PDF", audience: ["documents", "business"],
    keywords: ["print", "printing", "print ready"] }),
  w({ slug: "merge-and-compress-pdf", name: "Merge & Compress PDFs", icon: "combine", input: "pdf", multiple: true,
    goal: "Combine several PDFs into one small file.", description: "Merges in order, then compresses the result.",
    steps: [{ step: "pdf-merge" }, { step: "pdf-compress", params: { mode: "balanced" } }], output: "One compressed PDF", audience: ["documents", "business", "students"],
    keywords: ["merge", "combine", "together", "one pdf"] }),
  w({ slug: "pdf-pages-to-images", name: "PDF Pages to Images", icon: "images", input: "pdf",
    goal: "Share PDF pages as pictures.", description: "Converts every page to a 150 DPI JPG and compresses them.",
    steps: [{ step: "pdf-to-images", params: { dpi: 150 } }, { step: "compress", params: { quality: 82 } }], output: "One JPG per page", audience: ["personal", "social-media"],
    keywords: ["pdf to image", "pdf to jpg", "pages as photos"] }),
  w({ slug: "pdf-cover-thumbnail", name: "PDF Cover Thumbnail", icon: "image", input: "pdf",
    goal: "Create a preview image from the first page.", description: "Renders page 1 and makes a 600 × 800 WebP thumbnail.",
    steps: [{ step: "pdf-pages", params: { ranges: "1" } }, { step: "pdf-to-images", params: { dpi: 110 } }, size(600, 800, "inside"), webp(80)],
    output: "WebP thumbnail", audience: ["developers", "creators", "business"], keywords: ["pdf thumbnail", "cover image", "preview"] }),
  w({ slug: "pdf-to-clean-text", name: "PDF to Clean Text", icon: "scan-text", input: "pdf",
    goal: "Copy text out of a PDF without broken lines.", description: "Extracts text, then joins broken lines and removes extra spaces.",
    steps: [{ step: "pdf-text" }, { step: "text-clean", params: { trim: true, collapse: true, joinLines: true, emptyLines: false, html: false, quotes: true, dedupe: false } }],
    output: "Clean .txt", audience: ["students", "documents"], keywords: ["pdf text", "copy from pdf", "extract"] }),
  w({ slug: "extract-first-pages", name: "Extract First Pages", icon: "split", input: "pdf",
    goal: "Send only the first few pages of a long document.", description: "Keeps pages 1–3 and compresses the result.",
    steps: [{ step: "pdf-pages", params: { ranges: "1-3" } }, { step: "pdf-compress", params: { mode: "lossless" } }], output: "Short PDF", audience: ["documents", "business"],
    keywords: ["first pages", "extract", "sample pages"] }),

  // ── Data & JSON ──
  w({ slug: "api-ready-json", name: "API-Ready JSON", icon: "braces", popular: true, input: "json",
    goal: "Turn messy JSON into a compact, valid API payload.", description: "Validates, formats for review, removes nulls and empty values, then minifies.",
    steps: [{ step: "json-validate" }, { step: "json-format", params: { indent: "2" } }, { step: "json-clean" }, { step: "json-minify" }],
    output: "Minified, validated JSON", audience: ["developers"], keywords: ["api", "json", "payload", "clean json", "minify"] }),
  w({ slug: "readable-json", name: "Readable JSON for Review", icon: "braces", input: "json",
    goal: "Make JSON easy to read and diff.", description: "Validates, sorts keys alphabetically and formats with 2 spaces.",
    steps: [{ step: "json-validate" }, { step: "json-sort" }, { step: "json-format", params: { indent: "2" } }], output: "Sorted, formatted JSON", audience: ["developers"],
    keywords: ["readable", "pretty", "review", "diff json"] }),
  w({ slug: "config-cleanup", name: "Config Clean-Up", icon: "settings", input: "json",
    goal: "Tidy a JSON config file.", description: "Removes null values, sorts keys and formats with 2 spaces.",
    steps: [{ step: "json-validate" }, { step: "json-clean", params: { removeNull: true, removeEmpty: false } }, { step: "json-sort" }, { step: "json-format", params: { indent: "2" } }],
    output: "Clean config JSON", audience: ["developers"], keywords: ["config", "settings json", "package json"] }),
  w({ slug: "spreadsheet-to-api", name: "Spreadsheet to API JSON", icon: "table", input: "csv",
    goal: "Send spreadsheet data to an API.", description: "Converts CSV to a JSON array and minifies it.",
    steps: [{ step: "csv-to-json" }, { step: "json-minify" }], output: "Minified JSON array", audience: ["developers", "business"],
    keywords: ["csv", "excel", "spreadsheet to json", "import"] }),
  w({ slug: "csv-to-readable-json", name: "CSV to Readable JSON", icon: "file-json", input: "csv",
    goal: "Inspect CSV data as structured JSON.", description: "Converts CSV and pretty-prints the result.",
    steps: [{ step: "csv-to-json" }, { step: "json-format", params: { indent: "2" } }], output: "Formatted JSON", audience: ["developers", "business"],
    keywords: ["csv to json", "inspect csv"] }),
  w({ slug: "json-to-spreadsheet", name: "JSON to Spreadsheet", icon: "table", input: "json",
    goal: "Open API data in Excel or Google Sheets.", description: "Validates JSON and converts it to a clean CSV.",
    steps: [{ step: "json-validate" }, { step: "json-to-csv" }], output: "CSV file", audience: ["business", "developers"],
    keywords: ["json to excel", "json to csv", "export"] }),
  w({ slug: "json-to-env-base64", name: "JSON to Base64 (Env Var)", icon: "binary", input: "json",
    goal: "Store JSON credentials in a single environment variable.", description: "Validates, minifies and Base64-encodes JSON.",
    steps: [{ step: "json-validate" }, { step: "json-minify" }, { step: "base64-encode" }], output: "Base64 string", audience: ["developers"],
    keywords: ["env", "environment variable", "base64 json", "secret"] }),

  // ── Text ──
  w({ slug: "clean-pasted-text", name: "Clean Pasted Text", icon: "eraser", input: "text",
    goal: "Fix messy text copied from websites and emails.", description: "Strips HTML, straightens quotes, trims lines and removes extra spaces and empty lines.",
    steps: [{ step: "text-clean", params: { trim: true, collapse: true, emptyLines: true, joinLines: false, dedupe: false, html: true, quotes: true } }],
    output: "Clean text", audience: ["personal", "business", "students"], keywords: ["clean text", "messy", "paste", "format text"] }),
  w({ slug: "fix-pdf-copied-text", name: "Fix Text Copied from PDF", icon: "scan-text", input: "text",
    goal: "Join lines broken by PDF copy-paste.", description: "Joins broken lines into paragraphs and removes stray spaces.",
    steps: [{ step: "text-clean", params: { trim: true, collapse: true, joinLines: true, emptyLines: false, dedupe: false, html: false, quotes: true } }],
    output: "Paragraph text", audience: ["students", "documents"], keywords: ["pdf copy", "broken lines", "line breaks"] }),
  w({ slug: "headline-formatter", name: "Headline Formatter", icon: "case-sensitive", input: "text",
    goal: "Turn rough titles into clean Title Case headlines.", description: "Cleans spacing and applies proper Title Case.",
    steps: [{ step: "text-clean" }, { step: "text-case", params: { mode: "title" } }], output: "Title Case text", audience: ["creators", "business"],
    keywords: ["headline", "title case", "heading", "blog title"] }),
  w({ slug: "url-slug", name: "URL Slug Generator", icon: "link", input: "text",
    goal: "Create SEO-friendly URL slugs from titles.", description: "Cleans text and converts it to lowercase kebab-case.",
    steps: [{ step: "text-clean" }, { step: "text-case", params: { mode: "kebab" } }], output: "url-friendly-slug", audience: ["developers", "creators"],
    keywords: ["slug", "url", "permalink", "seo url"] }),
  w({ slug: "social-caption-check", name: "Social Caption Checker", icon: "message", input: "text",
    goal: "Make sure a caption fits Instagram's 2,200-character limit.", description: "Cleans the caption and checks its length.",
    steps: [{ step: "text-clean", params: { trim: true, collapse: true, emptyLines: false, html: true, quotes: true } }, { step: "text-limit", params: { maxChars: 2200, truncate: false } }],
    output: "Clean caption with length check", audience: ["social-media", "creators"], keywords: ["caption", "instagram caption", "character limit"] }),
  w({ slug: "dedupe-list", name: "Remove Duplicate Lines", icon: "list-checks", input: "text",
    goal: "Clean up lists of emails, names or keywords.", description: "Trims each line, removes empty lines and duplicates.",
    steps: [{ step: "text-clean", params: { trim: true, collapse: true, emptyLines: true, dedupe: true, html: false, quotes: false } }],
    output: "Unique lines", audience: ["business", "developers"], keywords: ["duplicate", "unique lines", "dedupe", "list"] }),
  w({ slug: "variable-names", name: "Text to Variable Names", icon: "code", input: "text",
    goal: "Turn labels into camelCase identifiers.", description: "Cleans text and converts it to camelCase.",
    steps: [{ step: "text-clean" }, { step: "text-case", params: { mode: "camel" } }], output: "camelCase text", audience: ["developers"],
    keywords: ["camelcase", "variable", "identifier"] }),
  w({ slug: "text-to-base64", name: "Text to Base64", icon: "binary", input: "text",
    goal: "Encode text for data URIs and headers.", description: "Trims text and encodes it as UTF-8 Base64.",
    steps: [{ step: "text-clean", params: { trim: true, collapse: false, html: false, quotes: false } }, { step: "base64-encode" }], output: "Base64 string", audience: ["developers"],
    keywords: ["base64", "encode text"] }),
];

export const workflowBySlug = (slug: string) => WORKFLOWS.find((w) => w.slug === slug);
export const workflowHref = (w: Workflow) => `/workflows/${w.slug}`;

export function workflowsForTool(stepIds: string[], limit = 4) {
  return WORKFLOWS.filter((w) => w.steps.some((s) => stepIds.includes(s.step))).slice(0, limit);
}
